flags: 
  train_flag : True
  live_plot_flag : False
  save_plot_flag : True
paths: 
  train_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/data/train"
  test_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/data/test"
  model_save_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/model/model.pth"
  model_load_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/model/model.pth"
  save_plot_path : "/home/argus-vision/vision/VisionTrainingGround/RCnet/results/loss_vs_epoch.png"

epochs : 50
